Controllers/AuthorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projekt_ASP.Interfaces;
using Projekt_ASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projekt_ASP.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class AuthorController : Controller
    {
        private readonly ICRUDAuthorRepository repository;

        public AuthorController(ICRUDAuthorRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Index()
        {
            return View(repository.FindAll());
        }

        public IActionResult Details(int id)
        {
            var author = repository.Find(id);
            return View(author);
        }

        public IActionResult Create()
        {
            return View(new Author());
        }

        [HttpPost]
        public IActionResult Create(Author author)
        {
            if (ModelState.IsValid)
            {
                repository.Add(author);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Create");
            }
        }

        public IActionResult Edit(int id)
        {
            var author = repository.Find(id);
            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Author editAuthor)
        {
            if (ModelState.IsValid)
            {
                repository.Update(id, editAuthor);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Edit");
            }
        }

        public IActionResult Delete(int id)
        {
            return View(repository.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                repository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projekt_ASP.Interfaces;
using Projekt_ASP.Models;

namespace Projekt_ASP.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class BookController : Controller
    {
        private readonly ICRUDBookRepository repository;

        public BookController(ICRUDBookRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var books = repository.FindAll();
            return View(books);
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = repository.FindAll().FirstOrDefault(x => x.BookId == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        public IActionResult Create([FromServices] ICRUDAuthorRepository authorRepository, [FromServices] ICRUDCategoryRepository categoryRepository)
        {
            ViewData["AuthorId"] = new SelectList(authorRepository.FindAll(), "AuthorId", "FullName");
            ViewData["CategoryId"] = new SelectList(categoryRepository.FindAll(), "CategoryId", "BookCategory");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("BookId,Name,PageCount,ReleaseDate,AuthorId,CategoryId,Price, Quantity")] Book book, [FromServices] ICRUDAuthorRepository authorRepository, [FromServices] ICRUDCategoryRepository categoryRepository)
        {
            if (ModelState.IsValid)
            {
                repository.Add(book);
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(authorRepository.FindAll(), "AuthorId", "FullName", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(categoryRepository.FindAll(), "CategoryId", "BookCategory", book.CategoryId);
            return View(book);
        }

        public IActionResult Edit(int id, [FromServices] ICRUDAuthorRepository authorRepository, [FromServices] ICRUDCategoryRepository categoryRepository)
        {
            var book = repository.Find(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(authorRepository.FindAll(), "AuthorId", "FullName", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(categoryRepository.FindAll(), "CategoryId", "BookCategory", book.CategoryId);
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("BookId,Name,PageCount,ReleaseDate,AuthorId,CategoryId,Price, Quantity")] Book book, [FromServices] ICRUDAuthorRepository authorRepository, [FromServices] ICRUDCategoryRepository categoryRepository, [FromServices] AppDbContext appDb)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    repository.Update(book);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId, appDb))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(authorRepository.FindAll(), "AuthorId", "FullName", book.AuthorId);
            ViewData["CategoryId"] = new SelectList(categoryRepository.FindAll(), "CategoryId", "BookCategory", book.CategoryId);
            return View(book);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = repository.FindAll().FirstOrDefault(x => x.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var book = repository.Find(id).BookId;
            repository.Delete(book);
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id, [FromServices] AppDbContext book)
        {
            return book.Books.Any(e => e.BookId == id);
        }
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Projekt_ASP.Interfaces;
using Projekt_ASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projekt_ASP.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class CategoryController : Controller
    {
        private readonly ICRUDCategoryRepository repository;

        public CategoryController(ICRUDCategoryRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Index()
        {
            return View(repository.FindAll());
        }

        public IActionResult Details(int id)
        {
            var category = repository.Find(id);
            return View(category);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                repository.Add(category);
                return View("Index", repository.FindAll());
            }
            else
            {
                return View("Create");
            }
        }

        public IActionResult Edit(int id)
        {
            return View(model: repository.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category editCategory)
        {
            if (ModelState.IsValid)
            {
                repository.Update(editCategory);
                return View("Index", repository.FindAll());
            }
            else
            {
                return View("Edit");
            }
        }

        public IActionResult Delete(int id)
        {
            return View(repository.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                repository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projekt ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body class="bg-white">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light text-white bg-dark  border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Customer" asp-action="Index">Projekt ASP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Book" asp-action="Index">Book List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Author" asp-action="Index">Author List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Category" asp-action="Index">Category List</a>
                        </li>
                        <li class="nav-item ">
                            @if (User.Identity.IsAuthenticated)
                            {
                                @if (User.IsInRole("Admin"))
                                {
                                    <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Index">Strona Admina</a>
                                }
                            }
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown" id="dropdown-menu">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @User.Identity.Name
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item btn">Action</a>
                                    <a class="dropdown-item btn">Ustawienia</a>
                                    <a class="dropdown-item btn" asp-controller="Account" asp-action="Logout">Wyloguj</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ml-5 position-relative">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 mb-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex justify-content-center">
            &copy; 2021 - Projekt ASP - Wszelkie prawa zastrzeżone
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>